### ISSUE TITLE
Stop Lessy from compiling every files

### ISSUE THREAD

**Issue by Mushr0000m** [Zizaco/lessy#3]
Hi !
I have put this in my config file : 
'origin'        => '../public/assets',
'destination'   => '../public/assets',
Because I have a folder for Front and one for Admin and need both Less files to be compliles. But the issue is that I have somes less files that only contains mixins and Lessy compile them to css. Is there a way to "exclude" a folder or files ? As a result I have several empty css files...
Thanks for this great packages :+1: 
Mushr00m

**Comment by Zizaco** [comment]
Hi @Mushr0000m,

You can do the following:

Toggle the `manual_compile_only` in your config file:

``` php
    ...
    /*
    |--------------------------------------------------------------------------
    | Manual Compilation
    |--------------------------------------------------------------------------
    |
    | This option will disable the autocompilation. So in order to actually
    | compile the less files you will have to call the compilation commands in
    | the before filter.
    |
    */

    'manual_compile_only' => true,
    ...
```

And register the Lessy alias in your `config/app.php`:

``` php
    'aliases' => array(
        'App'          => 'Illuminate\Support\Facades\App',
        ...
        'Lessy'        => 'Zizaco\Lessy\Facade',
    ),
```

Than finally, in your `app/filters.php`, update your `App::before` callback with `Lessy::compileSingleFile`:

``` php
App::before(function($request)
{
    ...

    // Compile less files if environment is not 'production'
    if(app()->environment() != 'production')
    {
        // You can use `compileSingleFile` to compile a single base.less
        // file that `@import`s all other files. The path is relative to the
        // `origin` in the config file.
        Lessy::compileSingleFile('admin/base.less');
        Lessy::compileSingleFile('front_end/base.less');
    }
});
```

Please, let me know if this works for you.

**Comment by Mushr0000m** [comment]
Thanks for your reply I'll try that soon !

**Comment by Mushr0000m** [comment]
I tried it. It works, but very slow and I don't know why. The normal system give me 55ms but doing the manual_compile_only it give me 560ms... Any idea why ?
